<?php
$cartas = [["palo" => " corazones", "valor" => "1", "imagen" => "cor_1.png"],
    ["palo" => "corazones", "valor" =>"2", "imagen" => "cor_2.png"],
    ["palo" => "corazones", "valor" =>"3", "imagen" => "cor_3.png"],
    ["palo" => "corazones", "valor" =>"4", "imagen" => "cor_4.png"],
    ["palo" => "corazones", "valor" =>"5", "imagen" => "cor_5.png"],
    ["palo" => "corazones", "valor" =>"6", "imagen" => "cor_6.png"],
    ["palo" => "corazones", "valor" =>"7", "imagen" => "cor_7.png"],
    ["palo" => "corazones", "valor" =>"8", "imagen" => "cor_8.png"],
    ["palo" => "corazones", "valor" =>"9", "imagen" => "cor_9.png"],
    ["palo" => "corazones", "valor" =>"10", "imagen" => "cor_10.png"],
    ["palo" => "corazones", "valor" =>"J", "imagen" => "cor_j.png"],
    ["palo" => "corazones", "valor" =>"Q", "imagen" => "cor_q.png"],
    ["palo" => "corazones", "valor" =>"K", "imagen" => "cor_k.png"],
    ["palo" => "rombos", "valor" =>"1", "imagen" => "rom_1.png"],
    ["palo" => "rombos", "valor" =>"2", "imagen" => "rom_2.png"],
    ["palo" => "rombos", "valor" =>"3", "imagen" => "rom_3.png"],
    ["palo" => "rombos", "valor" =>"4", "imagen" => "rom_4.png"],
    ["palo" => "rombos", "valor" =>"5", "imagen" => "rom_5.png"],
    ["palo" => "rombos", "valor" =>"6", "imagen" => "rom_6.png"],
    ["palo" => "rombos", "valor" =>"7", "imagen" => "rom_7.png"],
    ["palo" => "rombos", "valor" =>"8", "imagen" => "rom_8.png"],
    ["palo" => "rombos", "valor" =>"9", "imagen" => "rom_9.png"],
    ["palo" => "rombos", "valor" =>"10", "imagen" => "rom_10.png"],
    ["palo" => "rombos", "valor" =>"J", "imagen" => "rom_j.png"],
    ["palo" => "rombos", "valor" =>"Q", "imagen" => "rom_q.png"],
    ["palo" => "rombos", "valor" =>"K", "imagen" => "rom_k.png"],
    ["palo" => "picas", "valor" =>"1", "imagen" => "pic_1.png"],
    ["palo" => "picas", "valor" =>"2", "imagen" => "pic_2.png"],
    ["palo" => "picas", "valor" =>"3", "imagen" => "pic_3.png"],
    ["palo" => "picas", "valor" =>"4", "imagen" => "pic_4.png"],
    ["palo" => "picas", "valor" =>"5", "imagen" => "pic_5.png"],
    ["palo" => "picas", "valor" =>"6", "imagen" => "pic_6.png"],
    ["palo" => "picas", "valor" =>"7", "imagen" => "pic_7.png"],
    ["palo" => "picas", "valor" =>"8", "imagen" => "pic_8.png"],
    ["palo" => "picas", "valor" =>"9", "imagen" => "pic_9.png"],
    ["palo" => "picas", "valor" =>"10", "imagen" => "pic_10.png"],
    ["palo" => "picas", "valor" =>"J", "imagen" => "pic_j.png"],
    ["palo" => "picas", "valor" =>"Q", "imagen" => "pic_q.png"],
    ["palo" => "picas", "valor" =>"K", "imagen" => "pic_k.png"],
    ["palo" => "treboles", "valor" =>"1", "imagen" => "tre_1.png"],
    ["palo" => "treboles", "valor" =>"2", "imagen" => "tre_2.png"],
    ["palo" => "treboles", "valor" =>"3", "imagen" => "tre_3.png"],
    ["palo" => "treboles", "valor" =>"4", "imagen" => "tre_4.png"],
    ["palo" => "treboles", "valor" =>"5", "imagen" => "tre_5.png"],
    ["palo" => "treboles", "valor" =>"6", "imagen" => "tre_6.png"],
    ["palo" => "treboles", "valor" =>"7", "imagen" => "tre_7.png"],
    ["palo" => "treboles", "valor" =>"8", "imagen" => "tre_8.png"],
    ["palo" => "treboles", "valor" =>"9", "imagen" => "tre_9.png"],
    ["palo" => "treboles", "valor" =>"10", "imagen" => "tre_10.png"],
    ["palo" => "treboles", "valor" =>"J", "imagen" => "tre_j.png"],
    ["palo" => "treboles", "valor" =>"Q", "imagen" => "tre_q.png"],
    ["palo" => "treboles", "valor" =>"K", "imagen" => "tre_k.png"]
];

$jugadores = [0 => ["nombre" => "Paco", "foto" => "paco.png", "puntuacion" => 0],
    1 => ["nombre" => "Pepe", "foto" => "pepe.png", "puntuacion" => 0],
    2 => ["nombre" => "Juan", "foto" => "juan.png", "puntuacion" => 0],
    3 => ["nombre" => "Perico", "foto" => "perico.png", "puntuacion" => 0],
    4 => ["nombre" => "Andres", "foto" => "andres.png", "puntuacion" => 0]
];